Nationalities = {
    { name = 'Afghanistan', code = 'af' },
    { name = 'Albania', code = 'al' },
    { name = 'Algeria', code = 'dz' },
    { name = 'Argentina', code = 'ar' },
    { name = 'Australia', code = 'au' },
    { name = 'Austria', code = 'at' },
    { name = 'Bangladesh', code = 'bd' },
    { name = 'Belgium', code = 'be' },
    { name = 'Bolivia', code = 'bo' },
    { name = 'Brazil', code = 'br' },
    { name = 'Bulgaria', code = 'bg' },
    { name = 'Cambodia', code = 'kh' },
    { name = 'Canada', code = 'ca' },
    { name = 'Chile', code = 'cl' },
    { name = 'China', code = 'cn' },
    { name = 'Colombia', code = 'co' },
    { name = 'Costa Rica', code = 'cr' },
    { name = 'Croatia', code = 'hr' },
    { name = 'Cuba', code = 'cu' },
    { name = 'Czech Republic', code = 'cz' },
    { name = 'Denmark', code = 'dk' },
    { name = 'Dominican Republic', code = 'do' },
    { name = 'Ecuador', code = 'ec' },
    { name = 'Egypt', code = 'eg' },
    { name = 'El Salvador', code = 'sv' },
    { name = 'England', code = 'gb-eng' },
    { name = 'Estonia', code = 'ee' },
    { name = 'Ethiopia', code = 'et' },
    { name = 'Finland', code = 'fi' },
    { name = 'France', code = 'fr' },
    { name = 'Germany', code = 'de' },
    { name = 'Ghana', code = 'gh' },
    { name = 'Greece', code = 'gr' },
    { name = 'Guatemala', code = 'gt' },
    { name = 'Haiti', code = 'ht' },
    { name = 'Honduras', code = 'hn' },
    { name = 'Hungary', code = 'hu' },
    { name = 'Iceland', code = 'is' },
    { name = 'India', code = 'in' },
    { name = 'Indonesia', code = 'id' },
    { name = 'Iran', code = 'ir' },
    { name = 'Iraq', code = 'iq' },
    { name = 'Ireland', code = 'ie' },
    { name = 'Israel', code = 'il' },
    { name = 'Italy', code = 'it' },
    { name = 'Jamaica', code = 'jm' },
    { name = 'Japan', code = 'jp' },
    { name = 'Jordan', code = 'jo' },
    { name = 'Kenya', code = 'ke' },
    { name = 'South Korea', code = 'kr' },
    { name = 'Kuwait', code = 'kw' },
    { name = 'Latvia', code = 'lv' },
    { name = 'Lebanon', code = 'lb' },
    { name = 'Lithuania', code = 'lt' },
    { name = 'Malaysia', code = 'my' },
    { name = 'Mexico', code = 'mx' },
    { name = 'Morocco', code = 'ma' },
    { name = 'Netherlands', code = 'nl' },
    { name = 'New Zealand', code = 'nz' },
    { name = 'Nicaragua', code = 'ni' },
    { name = 'Nigeria', code = 'ng' },
    { name = 'Norway', code = 'no' },
    { name = 'Pakistan', code = 'pk' },
    { name = 'Panama', code = 'pa' },
    { name = 'Paraguay', code = 'py' },
    { name = 'Peru', code = 'pe' },
    { name = 'Philippines', code = 'ph' },
    { name = 'Poland', code = 'pl' },
    { name = 'Portugal', code = 'pt' },
    { name = 'Puerto Rico', code = 'pr' },
    { name = 'Romania', code = 'ro' },
    { name = 'Russia', code = 'ru' },
    { name = 'Saudi Arabia', code = 'sa' },
    { name = 'Scotland', code = 'gb-sct' },
    { name = 'Serbia', code = 'rs' },
    { name = 'Singapore', code = 'sg' },
    { name = 'Slovakia', code = 'sk' },
    { name = 'South Africa', code = 'za' },
    { name = 'Spain', code = 'es' },
    { name = 'Sweden', code = 'se' },
    { name = 'Switzerland', code = 'ch' },
    { name = 'Syria', code = 'sy' },
    { name = 'Taiwan', code = 'tw' },
    { name = 'Thailand', code = 'th' },
    { name = 'Trinidad and Tobago', code = 'tt' },
    { name = 'Turkey', code = 'tr' },
    { name = 'Ukraine', code = 'ua' },
    { name = 'United Arab Emirates', code = 'ae' },
    { name = 'United Kingdom', code = 'gb' },
    { name = 'United States', code = 'us' },
    { name = 'Uruguay', code = 'uy' },
    { name = 'Venezuela', code = 've' },
    { name = 'Vietnam', code = 'vn' },
    { name = 'Wales', code = 'gb-wls' },
}
